@hostname = localhost
@port = 3001
@host = http://{{hostname}}:{{port}}

###
GET {{host}}/api/users/ HTTP/1.1
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpwQG91dGxvb2suY29tIiwiaWF0IjoxNjg5NzExMTAzLCJleHAiOjE3NzYxMTExMDN9.Q5l4vAXLsduzi6TPc_S1Q9R4cmbMBUyBp_WSZ62Dw9Q

###
POST {{host}}/api/users/register HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "firstname": "Elvis",
  "lastname": "Presley",
  "email": "ep@outlook.com",
  "password": "ep"
}

###
POST {{host}}/api/users/login HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "email": "ep@outlook.com",
  "password": "ep"
}

###
GET {{host}}/api/users/64b6cbc1cfe232d02cf7cc74 HTTP/1.1
Accept: application/json


###
GET {{host}}/api/users/user HTTP/1.1
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVwQG91dGxvb2suY29tIiwiaWF0IjoxNjg5NzE0OTI2LCJleHAiOjE3NzYxMTQ5MjZ9.mmRWnfLc_JTpD93PxzfzJBsMwdoQGhjLQdjdKHS-Y60